Add missing components processing for artifact uploader: fixes missing stuff from broken builds and/or tests
<==== Mercurial data ====>
Branch: master

diff --git a/infra/jenkins_jobs/servers/ci-msk-new/macros/rsync.yaml b/infra/jenkins_jobs/servers/ci-msk-new/macros/rsync.yaml
--- a/infra/jenkins_jobs/servers/ci-msk-new/macros/rsync.yaml
+++ b/infra/jenkins_jobs/servers/ci-msk-new/macros/rsync.yaml
@@ -38,14 +38,13 @@
           RSYNC_SRC="${{RSYNC_SRC//\\//}}"
 
           # Check that components exist and if we are not allowed to have missing components and found on, die
-          if [ "{allow_missing}" == 'YES' ] ; then
-            if [ ! -e "${{RSYNC_SRC}}" ] ; then
-              echo "Missing components are allowed"
+
+          if [ ! -e "${{RSYNC_SRC}}" ] ; then
+            if [ "{allow_missing}" == 'YES' ] ; then
+              echo "Missing components (${{RSYNC_SRC}}) are allowed, continue"
               continue
-            fi
-          else
-            if [ ! -e "${{RSYNC_SRC}}" ] ; then
-              echo "Missing components are not allowed"
+            else
+              echo "Missing components (${{RSYNC_SRC}}) are not allowed, fail"
               exit 1
             fi
           fi
@@ -90,6 +89,12 @@
             ls -la "{dst_path}"
           else
             echo "{dst_path} does not exist yet"
+          fi
+
+          if [ "{allow_missing}" == 'YES' ] ; then
+            echo "Missing components are allowed ({allow_missing}), will not fail on lookup error"
+          else
+            echo "Missing components are not allowed ({allow_missing}), will fail on lookup error"
           fi
 
           echo "The components array is {components}"
@@ -138,6 +143,21 @@
           RSYNC_SRC="${{RSYNC_SRC//\\//}}"
 
           # NOTE: solution from above is not tested when dealing with local Windows machine. But it should work.
+
+          # Check that components exist and if we are not allowed to have missing components and found on, die
+          if $( \
+              ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null \
+              -p "${{RSYNC_PORT}}" "${{RSYNC_USER}}@${{RSYNC_HOST}}" \
+              test ! -e "${{RSYNC_SRC}}" \
+            ) ; then
+            if [ "{allow_missing}" == 'YES' ] ; then
+              echo "Missing components(${{RSYNC_SRC}}) are allowed, continue"
+              continue
+            else
+              echo "Missing components (${{RSYNC_SRC}} are not allowed, fail"
+              exit 1
+            fi
+          fi
 
           mkdir -p "${{RSYNC_DST%/*}}"
 
