CI-212: Display build description and color depending on pytest exit code
<==== Mercurial data ====>
Branch: master

diff --git a/infra/jenkins_jobs/servers/ci-msk-new/_templates/integration-tests/functional/distribution-functest.yaml b/infra/jenkins_jobs/servers/ci-msk-new/_templates/integration-tests/functional/distribution-functest.yaml
--- a/infra/jenkins_jobs/servers/ci-msk-new/_templates/integration-tests/functional/distribution-functest.yaml
+++ b/infra/jenkins_jobs/servers/ci-msk-new/_templates/integration-tests/functional/distribution-functest.yaml
@@ -113,6 +113,7 @@
         set -ex
         rm -rf   "build" "dist" "updates" "{workdir}"
         mkdir -p "build" "dist" "updates" "{workdir}"
+        rm -f unstable.flag
 
     - inject:
         properties-content: |
@@ -210,6 +211,7 @@
 
           cd nx_vms/func_tests
 
+            set +e
             export PYTEST_DEFAULTS_SECTION=ci  # init CI config
             # These params are required only for functests from 3.2 branch
             # --mediaserver-dist-path
@@ -217,7 +219,7 @@
             # --cloud-group
             # --vm-port-base
             # --vm-name-prefix
-            exec pytest \
+            pytest \
               --work-dir="$WORK_DIR" \
               --bin-dir="$BIN_DIR" \
               --mediaserver-installers-dir="$WORKSPACE/dist" \
@@ -242,6 +244,35 @@
               -k "$TEST_SELECT_EXPR" \
               $TEST_LIST
 
+            case "X$?" in
+            X0)
+              echo "PyTest - All tests were collected and passed successfully"
+              rm -f unstable.flag
+              exit 0
+            ;;
+            X1)
+              echo "PyTest - Tests were collected and run but some of the tests failed"
+              touch unstable.flag
+              exit 0
+            ;;
+            X2)
+              echo "PyTest - Test execution was interrupted by the user"
+              exit 2
+            ;;
+            X3)
+              echo "PyTest - Internal error happened while executing tests"
+              exit 3
+            ;;
+            X4)
+              echo "PyTest - pytest command line usage error"
+              exit 4
+            ;;
+            X5)
+              echo "PyTest - 	No tests were collected"
+              exit 5
+            ;;
+            esac
+
     - shell: |
         #!bash
         set -ex
@@ -259,6 +290,10 @@
 
     publishers:
     - mercurial/rm-repo-if-broken
+    - set-unstable-if-marked
+    - description-setter:
+        regexp: "'PyTest - (.*)'"
+        regexp-for-failed: "'PyTest - (.*)'"
     - postbuildscript:
         mark-unstable-if-failed: true
         builders:
diff --git a/infra/jenkins_jobs/servers/ci-msk-new/_templates/integration-tests/scalability/distribution-scalability-test.yaml b/infra/jenkins_jobs/servers/ci-msk-new/_templates/integration-tests/scalability/distribution-scalability-test.yaml
--- a/infra/jenkins_jobs/servers/ci-msk-new/_templates/integration-tests/scalability/distribution-scalability-test.yaml
+++ b/infra/jenkins_jobs/servers/ci-msk-new/_templates/integration-tests/scalability/distribution-scalability-test.yaml
@@ -121,6 +121,7 @@
         #!/bin/bash
         rm -rf   "build" "dist" "{workdir}"
         mkdir -p "build" "dist" "{workdir}"
+        rm -f unstable.flag
 
     - inject:
         properties-content: |
@@ -222,8 +223,9 @@
 
           cd nx_vms/func_tests
 
+            set +e
             export PYTEST_DEFAULTS_SECTION=ci  # init CI config
-            exec pytest \
+            pytest \
               --work-dir="$WORK_DIR" \
               --bin-dir="$BIN_DIR" \
               --mediaserver-installers-dir="$WORKSPACE/dist" \
@@ -264,9 +266,40 @@
         transactions_stage_duration=$TRANSACTIONS_STAGE_DURATION" \
               tests/scalability_test.py
 
+            case "X$?" in
+            X0)
+              echo "PyTest - All tests were collected and passed successfully"
+              rm -f unstable.flag
+              exit 0
+            ;;
+            X1)
+              echo "PyTest - Tests were collected and run but some of the tests failed"
+              touch unstable.flag
+              exit 0
+            ;;
+            X2)
+              echo "PyTest - Test execution was interrupted by the user"
+              exit 2
+            ;;
+            X3)
+              echo "PyTest - Internal error happened while executing tests"
+              exit 3
+            ;;
+            X4)
+              echo "PyTest - pytest command line usage error"
+              exit 4
+            ;;
+            X5)
+              echo "PyTest - 	No tests were collected"
+              exit 5
+            ;;
+            esac
     publishers:
     - mercurial/rm-repo-if-broken
-
+    - set-unstable-if-marked
+    - description-setter:
+        regexp: "'PyTest - (.*)'"
+        regexp-for-failed: "'PyTest - (.*)'"
     - failure-email:
         email-recipients: '{build_watchers}'
     - fixed-email:
