CI: Fix pytest exit code processing
<==== Mercurial data ====>
Branch: master

diff --git a/infra/jenkins_jobs/servers/ci-msk-new/_templates/integration-tests/functional/distribution-functest.yaml b/infra/jenkins_jobs/servers/ci-msk-new/_templates/integration-tests/functional/distribution-functest.yaml
--- a/infra/jenkins_jobs/servers/ci-msk-new/_templates/integration-tests/functional/distribution-functest.yaml
+++ b/infra/jenkins_jobs/servers/ci-msk-new/_templates/integration-tests/functional/distribution-functest.yaml
@@ -209,7 +209,7 @@
           # Test camera will respond only to requests from this address.
           VM_ADDRESS=192.168.13.7
 
-          cd nx_vms/func_tests
+          pushd nx_vms/func_tests
 
             set +e
             export PYTEST_DEFAULTS_SECTION=ci  # init CI config
@@ -244,34 +244,37 @@
               -k "$TEST_SELECT_EXPR" \
               $TEST_LIST
 
-            case "X$?" in
-            X0)
-              echo "PyTest - All tests were collected and passed successfully"
-              rm -f unstable.flag
-              exit 0
-            ;;
-            X1)
-              echo "PyTest - Tests were collected and run but some of the tests failed"
-              touch unstable.flag
-              exit 0
-            ;;
-            X2)
-              echo "PyTest - Test execution was interrupted by the user"
-              exit 2
-            ;;
-            X3)
-              echo "PyTest - Internal error happened while executing tests"
-              exit 3
-            ;;
-            X4)
-              echo "PyTest - pytest command line usage error"
-              exit 4
-            ;;
-            X5)
-              echo "PyTest - 	No tests were collected"
-              exit 5
-            ;;
-            esac
+            pytest_status="X$?"
+          popd
+
+          case "$pytest_status" in
+          X0)
+            echo "PyTest - All tests were collected and passed successfully"
+            rm -f unstable.flag
+            exit 0
+          ;;
+          X1)
+            echo "PyTest - Tests were collected and run but some of the tests failed"
+            touch unstable.flag
+            exit 0
+          ;;
+          X2)
+            echo "PyTest - Test execution was interrupted by the user"
+            exit 2
+          ;;
+          X3)
+            echo "PyTest - Internal error happened while executing tests"
+            exit 3
+          ;;
+          X4)
+            echo "PyTest - pytest command line usage error"
+            exit 4
+          ;;
+          X5)
+            echo "PyTest - 	No tests were collected"
+            exit 5
+          ;;
+          esac
 
     - shell: |
         #!bash
diff --git a/infra/jenkins_jobs/servers/ci-msk-new/_templates/integration-tests/realcamera/distribution-realcameratest.yaml b/infra/jenkins_jobs/servers/ci-msk-new/_templates/integration-tests/realcamera/distribution-realcameratest.yaml
--- a/infra/jenkins_jobs/servers/ci-msk-new/_templates/integration-tests/realcamera/distribution-realcameratest.yaml
+++ b/infra/jenkins_jobs/servers/ci-msk-new/_templates/integration-tests/realcamera/distribution-realcameratest.yaml
@@ -164,7 +164,7 @@
 
           TEST_TIMEOUT="$(( 60 * 60 ))" # 60 min
 
-          cd nx_vms/func_tests
+          pushd nx_vms/func_tests
 
             set +e
             export PYTEST_DEFAULTS_SECTION=ci  # init CI config
@@ -178,34 +178,38 @@
               --rct-camera-filter="$RCT_CAMERA_FILTER" \
               real_camera_tests/test_server.py::test_cameras
 
-            case "X$?" in
-            X0)
-              echo "PyTest - All tests were collected and passed successfully"
-              rm -f unstable.flag
-              exit 0
-            ;;
-            X1)
-              echo "PyTest - Tests were collected and run but some of the tests failed"
-              touch unstable.flag
-              exit 0
-            ;;
-            X2)
-              echo "PyTest - Test execution was interrupted by the user"
-              exit 2
-            ;;
-            X3)
-              echo "PyTest - Internal error happened while executing tests"
-              exit 3
-            ;;
-            X4)
-              echo "PyTest - pytest command line usage error"
-              exit 4
-            ;;
-            X5)
-              echo "PyTest - 	No tests were collected"
-              exit 5
-            ;;
-            esac
+            pytest_status="X$?"
+          popd
+
+          case "$pytest_status" in
+          X0)
+            echo "PyTest - All tests were collected and passed successfully"
+            rm -f unstable.flag
+            exit 0
+          ;;
+          X1)
+            echo "PyTest - Tests were collected and run but some of the tests failed"
+            touch unstable.flag
+            exit 0
+          ;;
+          X2)
+            echo "PyTest - Test execution was interrupted by the user"
+            exit 2
+          ;;
+          X3)
+            echo "PyTest - Internal error happened while executing tests"
+            exit 3
+          ;;
+          X4)
+            echo "PyTest - pytest command line usage error"
+            exit 4
+          ;;
+          X5)
+            echo "PyTest - 	No tests were collected"
+            exit 5
+          ;;
+          esac
+
     publishers:
     - mercurial/rm-repo-if-broken
     - set-unstable-if-marked
