CI: add jb functional tests, update scalability tests
<==== Mercurial data ====>
Branch: master

diff --git a/infra/jenkins_jobs/servers/ci-msk/templates/scalability-test.yaml b/infra/jenkins_jobs/servers/ci-msk/templates/scalability-test.yaml
--- a/infra/jenkins_jobs/servers/ci-msk/templates/scalability-test.yaml
+++ b/infra/jenkins_jobs/servers/ci-msk/templates/scalability-test.yaml
@@ -1,11 +1,36 @@
 # run scalability test as downstream job
+# params:
+# * branch
+# * platform
+# * upstream-jenkins
+# * upstream-project
+# * customization
+
 
 - job-template:
     name: '{branch}-scalability'
     node: scalability # spin_ubuntu_16
 
     description: |
-      Run scalability tests using {upstream_jenkins} Jenkins artifacts.
+      Run scalability tests using {upstream-jenkins} Jenkins artifacts.
+
+    parameters:
+      - bool:
+          name: CLEAN
+          default: false
+          description: Clean workspace before build
+      - string:
+          name: UPSTREAM_PROJECT
+          default: '{upstream-project}'
+          description: Name of upstream project to take artifacts to test from.
+      - string:
+          name: UPSTREAM_BUILD_NUMBER
+          default: lastCompletedBuild
+          description: BUILD_NUMBER of upstream project to take artifacts to test from. Default is last completed build.
+      - string:
+          name: CUSTOMIZATION
+          default: '{customization}'
+          description: Customization to test.
 
     wrappers:
     - build-keeper:
@@ -17,20 +42,15 @@
     - credentials-binding:
       - username-password-separated:
           credential-id: megatron-jenkins-login
-          username: upstream_user
-          password: upstream_password
+          username: UPSTREAM_USER
+          password: UPSTREAM_PASSWORD
       - username-password:
           credential-id: junk_shop_db
-          variable: junk_shop_db_credentials
-    - inject:
-        # Scalability test is run on remote (burbank) host.
-        # Junk-shop db host is mapped using 'ssh -R 5432:megatron:5432' by agent launch script.
-        properties-content: |
-          JUNK_SHOP_HOST=localhost
+          variable: JUNK_SHOP_DB_CREDENTIALS
 
     triggers:
     - reverse:
-        jobs: ci/{branch}
+        jobs: '{upstream-project}/{branch}'
         result: failure  # some platforms may be failed, but still ours may be built
 
     scm:
@@ -43,29 +63,62 @@
 
     builders:
 
-      - setup-scalability-env:
-          platform: '{platform}'
-          name: '{name}'
-          upstream_jenkins: '{upstream_jenkins}'
-          upstream_project: '{upstream_project}'
-          branch: '{branch}'
-          upstream_user: $upstream_user
-          upstream_password: $upstream_password
+      - shell: |
+          #!/bin/bash
+          set -ex
+
+          rm -rf dist/build_info.yaml bin/mediaserver.deb
+          mkdir -p dist work
+
+      - init-venv-linux:
+          requirements-files: >-
+            devtools/ci/junk_shop/requirements.txt
+            nx_vms/func_tests/requirements.txt
 
       - wget-artifact:
-          upstream_jenkins: '{upstream_jenkins}'
-          upstream_project: '{upstream_project}'
+          upstream-jenkins: '{upstream-jenkins}'
+          upstream-project: $UPSTREAM_PROJECT
+          upstream-user: $UPSTREAM_USER
+          upstream-password: $UPSTREAM_PASSWORD
           branch: '{branch}'
-          build_num: $build_num
+          build-num: $UPSTREAM_BUILD_NUMBER
           dest-dir: dist
-          artifact: $server_deb_path
+          artifact: build_info.yaml
+
+      - parse-build-info:
+          branch: '{branch}'
+          customization: $CUSTOMIZATION
+          platform: '{platform}'
+      - shell: |
+          set -xe
+          if [ -z "$SERVER_DEB_PATH" ]; then
+            echo "Error: upstream job $UPSTREAM_PROJECT/{branch} #$BUILD_NUM did not left mediaserver distributive for customization $CUSTOMIZATION"
+            exit 1
+          fi
+
+          if [ -z "$APPSERVER2_UT_PATH" ]; then
+            echo "Error: upstream job $UPSTREAM_PROJECT/{branch} #$BUILD_NUM did not left appserver2_ut test for customization $CUSTOMIZATION"
+            exit 1
+          fi
+
       - wget-artifact:
-          upstream_jenkins: '{upstream_jenkins}'
-          upstream_project: '{upstream_project}'
+          upstream-jenkins: '{upstream-jenkins}'
+          upstream-project: $UPSTREAM_PROJECT
+          upstream-user: $UPSTREAM_USER
+          upstream-password: $UPSTREAM_PASSWORD
           branch: '{branch}'
-          build_num: $build_num
+          build-num: $BUILD_NUM
           dest-dir: dist
-          artifact: $appserver2_ut_path
+          artifact: $SERVER_DEB_PATH
+      - wget-artifact:
+          upstream-jenkins: '{upstream-jenkins}'
+          upstream-project: $UPSTREAM_PROJECT
+          upstream-user: $UPSTREAM_USER
+          upstream-password: $UPSTREAM_PASSWORD
+          branch: '{branch}'
+          build-num: $BUILD_NUM
+          dest-dir: dist
+          artifact: $APPSERVER2_UT_PATH
 
       - shell: |
           #!/bin/bash
@@ -74,7 +127,15 @@
           mkdir -p bin
           chmod +x $(pwd)/dist/appserver2_ut  # wget does not preserve permissions
           ln -sf $(pwd)/dist/appserver2_ut bin/appserver2_ut
-          ln -sf $(pwd)/dist/$(basename $server_deb_path) bin/mediaserver.deb
+          ln -sf $(pwd)/dist/$(basename $SERVER_DEB_PATH) bin/mediaserver.deb
+      - inject:
+          properties-content: |
+            JUNK_SHOP_CAPTURE_DB=$JUNK_SHOP_DB_CREDENTIALS@{junk-shop-host}
+            BRANCH={branch}
+            BUILD_NUM=$BUILD_NUM
+            CUSTOMIZATION=$CUSTOMIZATION
+            PLATFORM={platform}
+
       - run-scalability-test:
           use_lightweight_servers: 'true'
           server_count: 50
