Further rework on build job
<==== Mercurial data ====>
Branch: master

diff --git a/infra/jenkins_jobs/servers/ci-msk-new/templates/installer-build.yaml b/infra/jenkins_jobs/servers/ci-msk-new/templates/installer-build.yaml
--- a/infra/jenkins_jobs/servers/ci-msk-new/templates/installer-build.yaml
+++ b/infra/jenkins_jobs/servers/ci-msk-new/templates/installer-build.yaml
@@ -68,6 +68,67 @@
 
     cmake_build_args_generator: ''
 
+    # this is a list of vars that not require during build process and should be removed
+    envvars_to_unset_during_build: >-
+      CMAKE_CONFIGURE_COMMAND
+      CLEAN_WORKSPACE
+      BUILD_URL
+      ROOT_BUILD_CAUSE_TIMERTRIGGER
+      TRIGGERED_BUILD_RUN_COUNT_helper_sync_hg
+      HUDSON_SERVER_COOKIE
+      MERCURIAL_REVISION_NUMBER
+      SSH_CLIENT
+      BUILD_TAG
+      LAST_TRIGGERED_JOB_NAME
+      BUILD_CONFIG_SHA_OLD
+      TRIGGERED_JOB_NAMES
+      ROOT_BUILD_CAUSE
+      CLEAN_CLONE
+      TRIGGERED_BUILD_NUMBERS_helper_sync_hg
+      CLEAN_BUILD
+      JOB_URL
+      TRIGGERED_BUILD_RUN_COUNT_helper_pull_component
+      MERCURIAL_REVISION_SHORT
+      RUN_CHANGES_DISPLAY_URL
+      BUILD_CAUSE_UPSTREAMTRIGGER
+      TRIGGERED_BUILD_NUMBER_helper_freeze_build_config
+      NX_VMS_COMMIT
+      WEBADMIN_COMPONENT_NAME
+      TRIGGERED_BUILD_NUMBER_helper_sync_hg
+      BUILD_DESCRIPTION
+      USE_WEBADMIN
+      JUNKSHOP_BASE_URL
+      TRIGGERED_BUILD_NUMBERS_helper_freeze_build_config
+      TRIGGERED_BUILD_RESULT_helper_freeze_build_config
+      RUN_DISPLAY_URL
+      TRIGGERED_BUILD_NUMBERS_helper_pull_component
+      TRIGGERED_BUILD_RESULT_helper_pull_component
+      JOB_NAME
+      BUILD_DISPLAY_NAME
+      RUNNER_URL
+      BUILD_ID
+      BUILD_CAUSE
+      JUNKSHOP_DB_HOST
+      TRIGGERED_BUILD_NUMBER_helper_pull_component
+      TRIGGERED_BUILD_RUN_COUNT_helper_freeze_build_config
+      JOB_BASE_NAME
+      MERCURIAL_REVISION
+      JENKINS_SERVER_COOKIE
+      BUILD_CONFIG_SHA
+      NODE_LABELS
+      LOGNAME
+      SSH_CONNECTION
+      NODE_NAME
+      COPYARTIFACT_BUILD_NUMBER_HELPER_FREEZE_BUILD_CONFIG
+      JOB_DISPLAY_URL
+      BUILD_NUMBER
+      HUDSON_COOKIE
+      JUNKSHOP_PROJECT_NAME
+      JUNKSHOP_URL
+      MERCURIAL_REPOSITORY_URL
+      TRIGGERED_BUILD_RESULT_helper_sync_hg
+      JUNKSHOP_HOST
+
     properties:
     - heavy-job:
         weight: 1
@@ -89,6 +150,21 @@
     - p_NX_VMS_COMMIT:
         default: '{branch}'
     - p_RUNNER_URL
+    - string:
+        name: CMAKE_CONFIGURE_COMMAND
+        default: >-
+          cmake
+          {cmake_configure_args_global}
+          {cmake_configure_args_pipeline}
+          {cmake_configure_args_platform}
+          {cmake_configure_args_customization}
+          -DbuildNumber=$BUILD_IDENTITY
+          -DcustomWebAdminPackageDirectory=$WORKSPACE/$WEBADMIN_COMPONENT_NAME
+    - string:
+        name:  CMAKE_BUILD_COMMAND
+        # FIXME: --config should be defined in project
+        default: >-
+          cmake --build . --config Release {cmake_build_args_generator}
 
     wrappers:
     # NOTE: There is a bug in jenkins: vars set here are read-only and can not be modified.
@@ -341,29 +417,49 @@
     - shell: |
         #!bash
         set -ex
-
-        # FIXME: deprecated
-        export environment=$WORKSPACE
-
-        cd "{build-dir}"
-
+        # Create bash script filled with args, unset too long envvars and
+        # execute cmake command
+        # ----------------------------------------------------------------------
+        cat > configure.sh <<BUILDSCRIPT
+        #!bash
+        # set -xe is is missing intentionally
         SECONDS=0
-        echo "Configuring project"
+
         # Log file must not exist
         rm -f "{cmake-configure-log}" # TODO: remove it in prep env
         test ! -f "{cmake-configure-log}"
-        cmake {cmake_configure_args_global} \
-              {cmake_configure_args_pipeline} \
-              {cmake_configure_args_platform} \
-              {cmake_configure_args_customization} \
-              -DbuildNumber=$BUILD_IDENTITY \
-              -DcustomWebAdminPackageDirectory=$WORKSPACE/$WEBADMIN_COMPONENT_NAME \
-              $WORKSPACE/nx_vms 2>&1 | tee "{cmake-configure-log}"
-        ec="${{PIPESTATUS[0]}}"
-        echo "Took $SECONDS seconds"
-        # Abort if first cmd in pipe failed
-        test "X${{ec}}" == "X0"
 
+        # remove all extra env vars
+        for ev in {envvars_to_unset_during_build} ; do
+          echo "Unsetting \${{ev}}=\${{!ev}}"
+          unset \$ev
+        done
+        # add env vars
+        # FIXME: deprecated
+        export environment=$WORKSPACE
+        echo "Env is:"
+        env
+        echo "Configuring project"
+        cd "{build-dir}"
+
+        echo "Cmake command - $CMAKE_CONFIGURE_COMMAND \$WORKSPACE/nx_vms"
+        $CMAKE_CONFIGURE_COMMAND \$WORKSPACE/nx_vms
+        ec=$?
+        echo "Took - \$SECONDS seconds"
+        echo "Exit code - \$ec"
+        exit "\$ec"
+        BUILDSCRIPT
+        # ----------------------------------------------------------------------
+        cat configure.sh
+        bash configure.sh 2>&1 | tee "{build-dir}/{cmake-configure-log}"
+        # Abort if buildscript failed
+        exit "${{PIPESTATUS[0]}}"
+
+    - shell: |
+        #!bash
+        set -ex
+        # TODO: rework in the same way as cmake stuff
+        pushd "{build-dir}"
         if [ "{use-ninja-clean-file}" == 'YES' ] ; then
           cleaner="${{WORKSPACE}}/devtools/ninja_clean/ninja_clean.py"
           if [ -f "$cleaner" ] ; then
@@ -379,25 +475,52 @@
             test "X${{ec}}" == "X0"
           fi
         fi
+        popd
 
-        export NINJA_STATUS="[%s/%t] %es "
-        if [ $OS == Windows_NT ] ; then
-          echo "WINDOWS" # TODO: set _MSPDBSRV_ENDPOINT_ here
-        fi
-        export _MSPDBSRV_ENDPOINT_=executor-$EXECUTOR_NUMBER
+    - shell: |
+        #!bash
+        set -ex
+        # Create bash script filled with args, unset too long envvars and
+        # execute cmake command
+        # ----------------------------------------------------------------------
+        cat > build.sh <<BUILDSCRIPT
+        #!bash
+        # set -xe is is missing intentionally
         SECONDS=0
-        echo "Building project"
+
         # Log file must not exist
         rm -f "{cmake-build-log}" # TODO: remove it in prep env
         test ! -f "{cmake-build-log}"
-        # FIXME: CMAKE_BUILD_TYPE should be defined in project
-        cmake --build . \
-              --config "${{CMAKE_BUILD_TYPE:-Release}}" \
-              {cmake_build_args_generator} 2>&1 | tee "{cmake-build-log}"
-        ec="${{PIPESTATUS[0]}}"
-        echo "Took $SECONDS seconds"
-        # Abort if first cmd in pipe failed
-        test "X${{ec}}" == "X0"
+
+        # remove all extra env vars
+        for ev in {envvars_to_unset_during_build} ; do
+          echo "Unsetting \${{ev}}=\${{!ev}}"
+          unset \$ev
+        done
+        # add env vars
+        export environment=$WORKSPACE
+        export NINJA_STATUS="[%s/%t] %es "
+        if [ "X${{OS}}" == "XWindows_NT" ] ; then
+          export _MSPDBSRV_ENDPOINT_=executor-$EXECUTOR_NUMBER
+        fi
+
+        echo "Env is:"
+        env
+        echo "Building project"
+        cd "{build-dir}"
+
+        echo "Cmake command - $CMAKE_BUILD_COMMAND"
+        $CMAKE_BUILD_COMMAND
+        ec=$?
+        echo "Took - \$SECONDS seconds"
+        echo "Exit code - \$ec"
+        exit "\$ec"
+        BUILDSCRIPT
+        # ----------------------------------------------------------------------
+        cat build.sh
+        bash build.sh 2>&1 | tee "{build-dir}/{cmake-build-log}"
+        # Abort if buildscript failed
+        exit "${{PIPESTATUS[0]}}"
 
     # STAGE: PUBLISH
     # ========================================
@@ -408,6 +531,10 @@
         artifacts: '{build-artifacts-min}'
         allow-empty: 'false'
         fingerprint: true
+
+    - archive:
+        artifacts: configure.sh,build.sh
+        allow-empty: true
 
     - postbuildscript:
         mark-unstable-if-failed: true
